services:
  postgres:
    container_name: task_postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - task_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: task_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - task_network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  task_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
